# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927d30e94c07ff2372c0d9a3964792357f0c305bb244b669cab33d3859d5788451840e76d171ee3de356f05ca676707eec75ebacc74e2ecbe774f9da89064e91

test:
  secret_key_base: 3be9dacf89f0b7393c1cba1e4b4bd0c9d83325b73aa08120edf3d60bf1e96bf0590897c35b8c35936120c639a7d44e11c2774008161e43c4ef09ea0bf57ea7d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
